import numpy as np    

a = np.array([12,32,12,42])
b = np.array([32,12,53,11])
c = np.add(a,b) 
print(c)
c = np.subtract(a,b)
print(c)
c = np.multiply(a,b)
print(c)
c = np.divide(a,b)
print(c)
c = np.power(a,b) 
print(c) 
c = np.mod(a,b) 
print(c)  
c = np.remainder(a,b)
print(c) 
c = np.divmod(a,b) 
print(c) 
c = np.absolute(a,b) 
print(c)